spring.application.name=kudamono
spring.mongodb.database=kudamono
spring.mongodb.uri=mongodb://localhost:27017/kudamono?authSource=admin
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG